# permissions for end users to edit playwrighttests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: playwright-operator
    app.kubernetes.io/managed-by: kustomize
  name: playwrighttest-editor-role
rules:
- apiGroups:
  - testing.my.domain
  resources:
  - playwrighttests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testing.my.domain
  resources:
  - playwrighttests/status
  verbs:
  - get
