# permissions for end users to view playwrighttests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: playwright-operator
    app.kubernetes.io/managed-by: kustomize
  name: playwrighttest-viewer-role
rules:
- apiGroups:
  - testing.my.domain
  resources:
  - playwrighttests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testing.my.domain
  resources:
  - playwrighttests/status
  verbs:
  - get
