---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - testing.my.domain
  resources:
  - playwrighttests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testing.my.domain
  resources:
  - playwrighttests/finalizers
  verbs:
  - update
- apiGroups:
  - testing.my.domain
  resources:
  - playwrighttests/status
  verbs:
  - get
  - patch
  - update
